name: build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run compile

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: package template
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: keycloak-nl-design-system.jar
          path: output/keycloak-nl-design-system.jar
          if-no-files-found: error
          retention-days: 7
          overwrite: true

      - name: Upload artifact to release
        if: startsWith(github.ref, 'refs/tags/v')
        run: gh release upload ${{ github.ref_name }} output/keycloak-nl-design-system.jar
        env:
          GH_TOKEN: ${{ github.token }}

